/**
 * Generate SIMULATION_ENGINES.md from the live engine registry.
 *
 * The catalog is derived, never hand-written: every engine already carries its
 * title, domain, description, references, parameter schema, and a worked example
 * in its `EngineSpec`, so the doc is a projection of the source of truth and can
 * never drift. Re-run with `pnpm docs:engines` after adding or changing an engine.
 */

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { describeEngine, engines } from '../src/lib/sim';
import type { ParamField } from '../src/lib/sim/core/param-fields';
// Single source of truth for domain labels — shared with the Lab & gallery UI so the
// docs can never drift from what the site shows (and no domain renders label-less).
import { domainLabel } from '../src/lib/sim/domain-labels';

function fieldType(f: ParamField): string {
  switch (f.kind) {
    case 'number':
      return f.integer ? 'integer' : 'number';
    case 'enum':
      return `enum(${f.options.join(' \\| ')})`;
    default:
      return f.kind;
  }
}

function fieldRange(f: ParamField): string {
  if (f.kind !== 'number') return '';
  const lo = f.min !== undefined ? `≥ ${f.min}` : '';
  const hi = f.max !== undefined ? `≤ ${f.max}` : '';
  return [lo, hi].filter(Boolean).join(', ');
}

function fieldDefault(f: ParamField): string {
  if (!('default' in f) || f.default === undefined) return f.optional ? '—' : '**required**';
  return `\`${typeof f.default === 'object' ? JSON.stringify(f.default) : String(f.default)}\``;
}

function paramsTable(fields: ParamField[]): string {
  if (fields.length === 0) return '_No parameters._\n';
  const rows = fields.map((f) => {
    const desc = (f.description ?? '').replace(/\|/g, '\\|');
    return `| \`${f.name}\` | ${fieldType(f)} | ${fieldDefault(f)} | ${fieldRange(f)} | ${desc} |`;
  });
  return [
    '| Param | Type | Default | Range | Description |',
    '|---|---|---|---|---|',
    ...rows,
  ].join('\n');
}

function engineSection(slug: string): string {
  const spec = engines.find((e) => e.slug === slug);
  if (!spec) return '';
  const d = describeEngine(spec);
  const refs =
    d.references.length > 0
      ? `\n**References**\n${d.references.map((r) => `- ${r}`).join('\n')}\n`
      : '';
  return `### \`${d.slug}\` — ${d.title}

${d.description}
${refs}
**Parameters**

${paramsTable(d.fields)}

**Example**

\`\`\`json
${JSON.stringify(d.example, null, 2)}
\`\`\`

_Run it: \`POST /api/lab/run { "engine": "${d.slug}", "params": … }\` or interactively at \`/lab/${d.slug}\`._
`;
}

function build(): string {
  const byDomain = new Map<string, string[]>();
  for (const e of engines) {
    const list = byDomain.get(e.domain) ?? [];
    list.push(e.slug);
    byDomain.set(e.domain, list);
  }

  const toc = [...byDomain.entries()]
    .map(([domain, slugs]) => {
      const links = slugs.map((s) => `[\`${s}\`](#${s})`).join(' · ');
      return `- **${domainLabel(domain)}** — ${links}`;
    })
    .join('\n');

  const sections = [...byDomain.entries()]
    .map(
      ([domain, slugs]) =>
        `## ${domainLabel(domain)}\n\n${slugs.map(engineSection).join('\n---\n\n')}`,
    )
    .join('\n\n');

  return `<!-- GENERATED by scripts/gen-engines-doc.ts — do not edit by hand. Run \`pnpm docs:engines\`. -->

# Simulation Engines

The OpenDiscover BioLab ships **${engines.length} deterministic simulation engines** across
${byDomain.size} domains of computational biology. Every engine is a *pure function* — no clock,
no network, no unseeded randomness — validated against known analytical or textbook values. The
same parameters always produce the same result and the same content hash, on every machine.

Each engine is registered in \`src/lib/sim/index.ts\` and conforms to the \`EngineSpec\` contract
(\`src/lib/sim/core/types.ts\`): a Zod parameter schema, a worked example, references, and a pure
\`run()\`. Run any engine three ways:

- **HTTP** — \`POST /api/lab/run\` with \`{ engine, params }\`
- **Interactive** — the \`/lab\` workbench (a form generated from the engine's schema + Vega-Lite charts)
- **Code** — \`import { runEngine } from '@/lib/sim'\`

## Catalog

${toc}

---

${sections}

## Authoring an engine

An engine is a single file under \`src/lib/sim/<domain>/<name>.ts\` that exports a \`spec\`:

\`\`\`ts
import { z } from 'zod';
import type { EngineSpec, SimResult } from '../core/types';
import { provenance } from '../core/types';

const params = z.object({
  x: z.number().positive().default(1),
});

export const spec: EngineSpec<z.input<typeof params>> = {
  slug: 'my-engine',
  title: 'My Engine',
  domain: 'systems-biology',
  version: '1.0.0',
  description: 'One paragraph: the model and its assumptions.',
  references: ['Author (Year). Title.'],
  paramsSchema: params,
  example: { x: 2 },
  run(raw): SimResult {
    const p = params.parse(raw);
    return {
      engine: 'my-engine',
      summary: \`Computed for x=\${p.x}\`,
      metrics: [{ key: 'x2', label: 'x squared', value: p.x ** 2 }],
      provenance: provenance('my-engine', '1.0.0', p),
    };
  },
};
\`\`\`

**Rules**

1. **Pure & deterministic** — no \`Date\`, no \`Math.random\` (use \`createRng\` from \`../core/prng\`),
   no network, no filesystem. Reuse \`../core/ode\` and \`../core/linalg\` rather than reinventing them.
2. **Parse inside \`run\`** — type params as \`z.input<...>\` and call \`.parse()\` first so defaults resolve.
3. **Test against known values** — a sibling \`*.test.ts\` must check the science against an analytical or
   textbook result, not merely that it doesn't throw. Cover determinism for any stochastic engine.
4. **Register it** — add one import + one array entry in \`src/lib/sim/index.ts\`.
5. **Regenerate this doc** — \`pnpm docs:engines\`.
`;
}

const out = join(process.cwd(), 'SIMULATION_ENGINES.md');
writeFileSync(out, build());
console.log(`Wrote ${out} (${engines.length} engines).`);
